<?php

namespace AppBundle\Repository;

/**
 * ITEMTYPERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ITEMTYPERepository extends \Doctrine\ORM\EntityRepository
{
}
