<?php

namespace AppBundle\Repository;

/**
 * SellingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellingsRepository extends \Doctrine\ORM\EntityRepository
{
}
