app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


app_api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/routes.yml"
